### ISSUE TITLE
RFM69.py code

### ISSUE THREAD

**Issue by hamishpyle** [mchobby/esp8266-upy#10]
Hey there! 
To help with my understanding, I am used ot using a network address and selected nodes from there for the sending // receiving. Does this mean that this wouldn't be compatible with your rfm69 module perchance? Given that it is based off the radiohead library? If not how would I implement havign a network address of 100? and a receipent node of 1?

Sorry I'm just very lost and any input would be helpful thank you!
Cheers

**Comment by mchobby** [comment]
You will find a complete example in this documentation page with two nodes having respectively addresses 120 & 100

https://wiki.mchobby.be/index.php?title=ENG-CANSAT-PICO-RFM69HCW-TEST

Cheers,
Dominique
