### ISSUE TITLE
Cannot use command mpremote on mcp230xx

### ISSUE THREAD

**Issue by Tiipiac** [mchobby/esp8266-upy#9]
Hi,
I am trying to use the command you provide in the readme to install your package on my esp running on micropython, but cannot.

The command: 
python.exe -m mpremote mip install github:mchobby/esp8266-upy/mcp230xx

The output:
Install github:mchobby/esp8266-upy/mcp230xx
Installing github:mchobby/esp8266-upy/mcp230xx/package.json to /lib
Package may be partially installed
mpremote: Package not found: github:mchobby/esp8266-upy/mcp230xx/package.json

It's my first time using micropython, but after searching around I could not find an answer to my issue. Could you help me out there?
Thanks!

**Comment by Tiipiac** [comment]
I cannot find the package.json, and still have the same issue. Are you sure you pushed the updates on master?

**Comment by mchobby** [comment]
Hi Tiipiac,
Thanks for coming back.
There is an evil eye looking over this lib :.-|
I now push the change online.
Dominique
